[package]
name = "casbin-grpc"
version = "0.1.0"
authors = ["hackerchai <i@hackerchai.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
